# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
array3X3 = np.array([[1.07, 0.44, 1.5],[0.27, 1.13, 1.72],[0.27, 1.13, 1.72]])
array3X3

array([[1.07, 0.44, 1.5 ],
       [0.27, 1.13, 1.72],
       [0.27, 1.13, 1.72]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [6]:
array3X3 = np.array([[1.07, 0.44, 1.5],[0.27, 1.13, 1.72],[0.27, 1.13, 1.72],[0.55, 8.13, 1.72],[0.78, 3.5, 2.5]])

norm = np.linalg.norm(array3X3)
normal_array = array3X3/norm
print(normal_array)

[[0.10664276 0.0438531  0.14949919]
 [0.02690985 0.11262273 0.17142574]
 [0.02690985 0.11262273 0.17142574]
 [0.05481637 0.81028563 0.17142574]
 [0.07773958 0.34883145 0.24916532]]


# 5.  How to find common values between two arrays?

In [7]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [8]:
from datetime import datetime, timedelta 
  
  
# Get today's date 
presentday = datetime.now() # or presentday = datetime.today() 
  
# Get Yesterday 
yesterday = presentday - timedelta(1) 
  
# Get Tomorrow 
tomorrow = presentday + timedelta(1) 
  
  
# strftime() is to format date according to 
# the need by converting them to string 
print("Yesterday = ", yesterday.strftime('%d-%m-%Y')) 
print("Today = ", presentday.strftime('%d-%m-%Y')) 
print("Tomorrow = ", tomorrow.strftime('%d-%m-%Y'))

Yesterday =  26-07-2020
Today =  27-07-2020
Tomorrow =  28-07-2020


# 7. Consider two random array A and B, check if they are equal

In [10]:
an_array = np.array([[1,2],[3,4]])
an_arrayb = np.array([[1,2],[2,4]])
another_array = np.array([[1,2],[3,4]])

comparison = an_array == another_array
comparisonb = an_arrayb == another_array

equal_arrays = comparison.all()
equal_arraysb = comparisonb.all()

print(equal_arrays)
print(equal_arraysb)

True
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [11]:
x = np.random.random(15)
print("Original array:")
print(x)
x[x.argmax()] = -1
print("Maximum value replaced by -1:")
print(x)

Original array:
[0.97025853 0.72697789 0.31386506 0.21043985 0.97081096 0.02000338
 0.63247088 0.98416503 0.42912114 0.83203415 0.46117011 0.24132718
 0.5114885  0.07820575 0.76719585]
Maximum value replaced by -1:
[ 0.97025853  0.72697789  0.31386506  0.21043985  0.97081096  0.02000338
  0.63247088 -1.          0.42912114  0.83203415  0.46117011  0.24132718
  0.5114885   0.07820575  0.76719585]


# 9. How to print all the values of an array?

In [13]:
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [14]:
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[0.87143469 0.11317008 0.24854055 0.40105017 0.57320176 0.59914148
  0.89090098 0.68877677 0.82068276 0.00501579]
 [0.9379787  0.7019145  0.27799272 0.36753806 0.80007541 0.1992239
  0.69966132 0.24392306 0.44589692 0.11746452]
 [0.09830958 0.51948649 0.94750386 0.62138838 0.0440887  0.92730458
  0.69565044 0.18733045 0.24089913 0.3105171 ]
 [0.30537854 0.21687833 0.75376314 0.83692739 0.02432144 0.49100338
  0.98198435 0.34130058 0.96946322 0.35745536]
 [0.06410423 0.03344401 0.65051439 0.48285249 0.61710224 0.01346252
  0.95817786 0.07448236 0.48405331 0.30228678]]

Subtract the mean of each row of the said matrix:

[[ 0.35024318 -0.40802143 -0.27265095 -0.12014133  0.05201025  0.07794997
   0.36970948  0.16758527  0.29949126 -0.51617571]
 [ 0.45881178  0.22274759 -0.20117419 -0.11162885  0.3209085  -0.27994301
   0.22049441 -0.23524385 -0.03326999 -0.36170239]
 [-0.36093829  0.06023862  0.48825599  0.16214051 -0.41515917  0.46805671
   0.23640257 -0.27191742 -0.21834874 -0.14873077

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

In [19]:
X = np.array([[1.07, 0.44, 1.5],[0.27, 1.13, 1.72],[0.27, 1.13, 1.72],[0.55, 8.13, 1.72],[0.78, 3.5, 2.5]])
Y = np.array([[1, 0.44, 1.5],[0.5, 1.13, 1.2],[0.7, 1.03, 1.2],[0.65, 2.13, 1.2],[8.78, 3.52, 2.52]])
 
    Z = np.dot(X, Y)
    Z

IndentationError: unexpected indent (<ipython-input-19-5992252996c6>, line 4)

# 13.How to find the most frequent value in an array?

In [22]:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[7 2 2 7 9 2 3 6 2 3 4 9 7 3 1 7 1 6 7 8 9 2 8 1 6 4 8 6 4 3 7 7 3 0 8 5 6
 9 3 7]
Most frequent value in the above array:
7


# 14.How to get the n largest values of an array

In [23]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [21]:
arra1 = np.array([("Yasemin Rayner", 88.5, 90),
                 ("Ayaana Mcnamara", 87, 99),
             ("Jody Preece", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Yasemin Rayner' '88.5' '90']
 ['Ayaana Mcnamara' '87' '99']
 ['Jody Preece' '85.5' '91']]

Record array;
[(b'Yasemin Rayner', 88.5, 90) (b'Ayaana Mcnamara', 87. , 99)
 (b'Jody Preece', 85.5, 91)]
